### ISSUE TITLE
Active, Inactive, retired

### ISSUE THREAD

**Issue by sythe7448** [bravecollective/doctrine-contracts#11]
Adding a feature so we can put active doctrines at the top, Inactive in the middle and retired at the bottom.

**Comment by dreadscape** [comment]
Similar was going to ask for flag active, dormant. Ordering would be a bonus.

**Comment by carlgevans** [comment]
How would you like it to look? A corner image similar to the Official tag but in the bottom right corner saying either 'Active' or 'Retired' ? Are two statuses (say a boolean isActive) enough?

**Comment by dreadscape** [comment]
That would be fine, except active or dormant. Retired should be deleted
IMHO. Also incase you have not noticed  BNI has moved to V-3YG7, not the
final destination yet.

How would you like it to look? A corner image similar to the Official tag
but in the bottom right corner saying either 'Active' or 'Retired' ? Are
two statuses (say a boolean isActive) enough?

—
Reply to this email directly or view it on
GitHubhttps://github.com/bravecollective/doctrine-contracts/issues/11#issuecomment-41952403
.

**Comment by carlgevans** [comment]
This has been implemented in v4.6, now live. The issue can be closed.
